basePath: /api/v1alpha1
consumes:
- application/json
definitions:
  config.Class:
    properties:
      classes:
        description: Classes are the names of classes in this group.
        items:
          type: string
        type: array
      domain:
        description: Domain of the classes, all must be in the same domain.
        type: string
      name:
        description: Name is the short name for a group of classes.
        type: string
    type: object
  config.ClassSpec:
    properties:
      classes:
        description: |-
          Classes is a list of class names to be selected from the domain.
          If absent, all classes in the domain are selected.
        items:
          type: string
        type: array
      domain:
        description: Domain is the domain for selected classes.
        type: string
    type: object
  config.Config:
    properties:
      aliases:
        description: Aliases defines short names for groups of related classes.
        items:
          $ref: '#/definitions/config.Class'
        type: array
      include:
        description: Include lists additional configuration files or URLs to include.
        items:
          type: string
        type: array
      rules:
        description: Rules define the relationships that korrel8r will follow.
        items:
          $ref: '#/definitions/config.Rule'
        type: array
      stores:
        description: Stores is a list of store configurations.
        items:
          $ref: '#/definitions/korrel8r.StoreConfig'
        type: array
    type: object
  config.Configs:
    additionalProperties:
      $ref: '#/definitions/config.Config'
    type: object
  config.ResultSpec:
    properties:
      query:
        description: Query template generates a query object suitable for the goal
          store.
        type: string
    type: object
  config.Rule:
    properties:
      goal:
        allOf:
        - $ref: '#/definitions/config.ClassSpec'
        description: Goal specifies the set of classes that this rule can produce.
      name:
        description: |-
          Name is a short, descriptive name.
          If omitted, a name is generated from Start and Goal.
        type: string
      result:
        allOf:
        - $ref: '#/definitions/config.ResultSpec'
        description: |-
          TemplateResult contains templates to generate the result of applying this rule.
          Each template is applied to an object from one of the `start` classes.
          If any template yields a blank string or an error, the rule does not apply.
      start:
        allOf:
        - $ref: '#/definitions/config.ClassSpec'
        description: Start specifies the set of classes that this rule can apply to.
    type: object
  korrel8r.Constraint:
    properties:
      end:
        description: Exclude results after End.
        type: string
      limit:
        description: Max number of entries to return.
        type: integer
      start:
        description: Exclude results before Start.
        type: string
    type: object
  korrel8r.StoreConfig:
    additionalProperties:
      type: string
    type: object
  rest.Classes:
    additionalProperties:
      type: string
    description: Classes maps class names to a short description.
    type: object
  rest.Domain:
    description: Domain configuration information.
    properties:
      errors:
        items:
          type: string
        type: array
      name:
        type: string
      stores:
        items:
          $ref: '#/definitions/korrel8r.StoreConfig'
        type: array
    type: object
  rest.Edge:
    properties:
      goal:
        description: Goal is the class name of the goal node.
        example: domain:class
        type: string
      rules:
        description: Rules is the set of rules followed along this edge (optional).
        items:
          $ref: '#/definitions/rest.Rule'
        type: array
      start:
        description: Start is the class name of the start node.
        type: string
    type: object
  rest.GoalsRequest:
    description: Starting point for a goals search.
    properties:
      goals:
        description: Goal classes for correlation.
        example:
        - domain:class
        items:
          type: string
        type: array
      start:
        allOf:
        - $ref: '#/definitions/rest.Start'
        description: Start of correlation search.
    type: object
  rest.Graph:
    description: Graph resulting from a correlation search.
    properties:
      edges:
        items:
          $ref: '#/definitions/rest.Edge'
        type: array
      nodes:
        items:
          $ref: '#/definitions/rest.Node'
        type: array
    type: object
  rest.NeighboursRequest:
    description: Starting point for a neighbours search.
    properties:
      depth:
        description: Max depth of neighbours graph.
        type: integer
      start:
        allOf:
        - $ref: '#/definitions/rest.Start'
        description: Start of correlation search.
    type: object
  rest.Node:
    properties:
      class:
        description: Class is the full class name in "DOMAIN:CLASS" form.
        example: domain:class
        type: string
      count:
        description: Count of results found for this class, after de-duplication.
        type: integer
      queries:
        description: Queries yielding results for this class.
        items:
          $ref: '#/definitions/rest.QueryCount'
        type: array
    type: object
  rest.QueryCount:
    description: Query run during a correlation with a count of results found.
    properties:
      count:
        description: Count of results or -1 if the query was not executed.
        type: integer
      query:
        description: Query for correlation data.
        type: string
    type: object
  rest.Rule:
    properties:
      name:
        description: Name is an optional descriptive name.
        type: string
      queries:
        description: Queries generated while following this rule.
        items:
          $ref: '#/definitions/rest.QueryCount'
        type: array
    type: object
  rest.Start:
    description: Starting point for correlation.
    properties:
      class:
        description: Class of starting objects
        type: string
      constraint:
        allOf:
        - $ref: '#/definitions/korrel8r.Constraint'
        description: Constraint (optional) to limit the results.
      objects:
        description: Objects serialized as JSON to, must be of start class.
        type: object
      queries:
        description: Queries for starting objects, must return the start class.
        items:
          type: string
        type: array
    type: object
info:
  contact:
    name: Project Korrel8r
    url: https://github.com/korrel8r/korrel8r
  description: REST API for the Korrel8r correlation engine.
  license:
    name: Apache 2.0
    url: https://github.com/korrel8r/korrel8r/blob/main/LICENSE
  title: REST API
  version: v1alpha1
paths:
  /configuration:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Configs'
      summary: Dump configuration files and their contents.
      tags:
      - configuration
  /domains:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.Domain'
            type: array
      summary: List all configured domains and stores.
      tags:
      - configuration
  /domains/{domain}/classes:
    get:
      parameters:
      - description: Domain to get classes from.
        in: path
        name: domain
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Classes'
      summary: Get class names and descriptions for the domain.
      tags:
      - configuration
  /graphs/goals:
    post:
      parameters:
      - description: include rules in graph edges
        in: query
        name: withRules
        type: boolean
      - description: search from start to goal classes
        in: body
        name: start
        required: true
        schema:
          $ref: '#/definitions/rest.GoalsRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Graph'
      summary: Create a correlation graph from start objects to goal queries.
      tags:
      - search
  /graphs/neighbours:
    post:
      parameters:
      - description: include rules in graph edges
        in: query
        name: withRules
        type: boolean
      - description: search from neighbours
        in: body
        name: start
        required: true
        schema:
          $ref: '#/definitions/rest.NeighboursRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Graph'
      summary: Create a correlation graph of neighbours of a start object to a given
        depth.
      tags:
      - search
  /lists/goals:
    post:
      parameters:
      - description: search from start to goal classes
        in: body
        name: start
        required: true
        schema:
          $ref: '#/definitions/rest.GoalsRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.Node'
            type: array
      summary: Generate a list of goal nodes related to a starting point.
      tags:
      - search
  /objects:
    get:
      parameters:
      - description: query string
        in: query
        name: query
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: object
            type: array
      summary: Execute a query, returns a list of JSON objects.
      tags:
      - search
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
