apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
- https://github.com/grafana/loki/operator/config/overlays/development?ref=v2.7.4&timeout=600s
#- ../../../../grafana/loki/operator/config/overlays/development/

configMapGenerator:
- files:
  - controller_manager_config.yaml
  behavior: replace
  name: manager-config
  namespace: logging
