---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: openshift-tempo-operator
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucket: tempo
  endpoint: http://minio.minio.svc:9000
type: Opaque
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo-stack
  namespace: openshift-tempo-operator
spec:
  storageSize: 1Gi
  storage:
    secret:
      name: minio
      type: s3
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
---
