name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - uses: actions/cache@v4
        with:
          path: |
            ~/go
            ~/.cache/golangci-lint
          key: cache-${{ runner.os }}-${{ runner.arch }}

      - name: Lint
        run: |
          make GOLANGCI_LINT_CACHE=~/.cache/golangci-lint lint
          git diff --exit-code

      - name: Test
        run: make test-skip
